### PR TITLE
Add support for published date

### PR DESCRIPTION
**Pull request by joshknowles**
I've added support for parsing the pubDate for RSS and published / updated date for Atom and exposing as published.

### CODE REVIEW

**Comment by arttu** [comment]
Sorry for a delayed answer.

I've been too busy lately, but I try to look this through in more detail tomorrow.

To my opinion, the instantiating and parsing at once is a matter of a separate pull request.
I've previously planned to change this behavior for quite a while. Let's see how it all comes together.

**Comment by graaff** [comment]
Any chance of the published date part of the request getting in? I'm currently migrating my code from simple_rss and this is the only regression I'm seeing.

**Comment by arttu** [comment]
Oh, I had completely forgotten these pull requests.

This and #3 are now merged to master and I'll publish a new gem version now.

**Comment by graaff** [comment]
Thanks!

**Pull request closed without merging**
